### ISSUE TITLE
Feature request: verbose commands

### ISSUE THREAD

**Issue by joker314** [towerofnix/scratch-client-omg#3]
I find it difficult to memorise all these one-letter commands. How about, as well as short codes, there are longer ones.

For example, `help` will give you a list of long commands; whereas `?` will give you a list of short ones.

Leaving a comment could be `send`
Reading more comments could be `more`
Quitting could be `quit`

etc.

**Comment by towerofnix** [comment]
Good idea. Take a look at the commit I just pushed (a23ac798f201721e4a7af84d4711dd70ca07dad5)! Hopefully this'll help. (And maybe you'll - *naturally* - get used to the short codes as you go too! :) )

**Comment by joker314** [comment]
Nice job; closing. 👍
