### ISSUE TITLE
Trim unnecessary line breaks

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/scratch-client-omg#34]
I ran into project 261210105 (https://scratch.mit.edu/projects/261210105/) which apparently has a ton of line breaks in its description (see https://api.scratch.mit.edu/projects/261210105). These filled up the whole screen.

Code should go in the `util.wrap` function. I'm thinking up to 3 should in a row should be allowed.

**Comment by towerofnix** [comment]
Labelled "web feature" because this is apparently something that the website deals with!

**Comment by joker314** [comment]
Note: it's not just line breaks, all whitespace too.

**Comment by towerofnix** [comment]
Sounds like a regex is appropriate here. I'm not super familiar with groups - would doing `([\s])($1){2,}` work to match 3+ in a row of the same whitespace character? (I want to count each type of whitespace separately. Sometimes people but a space at the end of their paragraph, and if we count all whitespace together, then that one space would make it so they could have one less line break than if it wasn't there - not something we want.)

**Comment by joker314** [comment]
You don't *need* the square brackets, in JS  \ in the RegEx and $ in the replace text when referencing capturing groups I think, but otherwise, that looks like a perfect RE.

I was actually thinking maybe we should replace whitespace with "(10 more spaces not displayed)" in a different colour. Thoughts on this?

**Comment by towerofnix** [comment]
Thanks for the regex tips!

>I was actually thinking maybe we should replace whitespace with "(10 more spaces not displayed)" in a different colour. Thoughts on this?

Definitely interesting. I wonder if this should only be done for line breaks? Replacing, for example, five spaces with ` (3 more spaces not displayed) ` does not look very good; but neither does displaying all five spaces. But for line breaks I think it's okay. Thoughts?

**Comment by joker314** [comment]
Also, is it okay to have \n\s repeated many times remain as-is?

**Comment by towerofnix** [comment]
Good point. No, whitespace-only lines should be treated the same as consecutive empty lines. Probably the easiest way to do this is to just take a first pass and replace whitespace-only lines with empty lines. `replace(/^\s+$/g, '')` would work I think?

**Comment by towerofnix** [comment]
Alright, fixed! And yikes, take a look at how many blank lines there were in the example project!

!["**Notes and Credits:** Time taken: 9-12 hours...Enjoy <33", then "(868 more blank lines not displayed)", then "sigh"](https://user-images.githubusercontent.com/9948030/48366327-dc8afa80-e683-11e8-9662-a4f5628009e2.png)
