### ISSUE TITLE
trying to find headers

### ISSUE THREAD

**Issue by MathMan05** [towerofnix/scratch-client-omg#38]
I've looked but I just can't find the headers for this [code](https://github.com/towerofnix/scratch-client-omg/blob/f5fd986d3cd1fea6ac6a737c34275c22499434ee/lib/comments.js#L347)... I see you made it, do you remember what they are?

**Comment by MathMan05** [comment]
nm I found em I think

**Comment by MathMan05** [comment]
although when I trying to post it just gives me the HTML to the login screen, is this the right body or is something missing? {"content":"test","parentid":"","commentee_id":"mathman05"}
also are these the right headers?
[["Cookie", "scratchsessionsid=token; scratchcsrftoken=a;"], ["X-CSRFToken", "a"], ["referer", "https://scratch.mit.edu"]]

**Comment by towerofnix** [comment]
Headers look good, body seems *mostly* right - I'll point out that `commentee_id` is the person you're *replying to* (and an ID, not a username), though, so unless you're replying to someone's existing comment you should leave that empty. (commentee_id determines who shows up in the link at the start of a reply, e.g. when you reply to a comment I make it shows "@_nix" at the start.)

You could try fixing that, but I'm not 100% sure it would be enough to fix the issue of getting the login screen.

What's the specific/complete URL you are posting to?

**Comment by MathMan05** [comment]
https://scratch.mit.edu/site-api/comments/user/mathman05/add/

**Comment by towerofnix** [comment]
Hmmm, can I see your code? I'm not 100% sure what the issue is here, sorry, but here's a guess:

The only way it seems to show the login page (in my testing) is when the request method is `GET` instead of `POST`. (My post request just gets me a 403 error when auth fails.) Maybe it is somehow sending get instead of post?

**Comment by MathMan05** [comment]
wait, how do you specify a project?

**Comment by towerofnix** [comment]
What do you mean? Why do you want to specify a project?

**Comment by MathMan05** [comment]
to comment on, as right now it has no way of know which one to comment on.

**Comment by towerofnix** [comment]
For sending comments on project pages, post to `https://scratch.mit.edu/site-api/comments/project/<project id>/add/`. Otherwise the headers and body all work the same way.

**Comment by MathMan05** [comment]
ok
