### ISSUE TITLE
Feature request: navigating to other profiles

### ISSUE THREAD

**Issue by joker314** [towerofnix/scratch-client-omg#4]
As far as I can tell, it's not possible to type a username and view their profile. You can only get to them if they left a comment.

I might be wrong though. *shrugs*

**Comment by ktrvs** [comment]
That would be nice, I've just been changing the username at the bottom of the  `index.js` file and then restarting the client.

**Comment by towerofnix** [comment]
Yes it absolutely is! Try `node . (username)`. (You can also try `node . (project ID) project` to view a project!)

It should be documented better - honestly, I should just add this to the readme.

**Comment by towerofnix** [comment]
Okay, I've added basic usage notes to the readme. Try out `node . (username)` and tell me if that works; if it doesn't, then that's a bug that I'll need to fix :)

**Comment by joker314** [comment]
@towerofnix Oh, cool, it works _tada_; but I don't want to have to restart the app each time I want to navigate to a new user

**Comment by towerofnix** [comment]
Yeah, I need to figure out how to implement "global" actions, so that you can (for example) go to a user's profile without quitting the app. Or view your messages. I wonder how that should actually work, though... maybe pressing `#` could show a list of frequent global commands like those?

**Comment by towerofnix** [comment]
Alright, I've implemented a super simple menu to Go to Places that shows up when you press `#`. (Arguably, it should also show up as soon as you run the program, but I prefer it to go to my profile.. :) )

**Comment by joker314** [comment]
This looks fixed. Thanks again @towerofnix for putting so much of your time into this awesome project!

**Comment by towerofnix** [comment]
Thanks for giving suggestions and ideas :)

**Comment by ktrvs** [comment]
> Thanks again @towerofnix for putting so much of your time into this awesome project!

Yep, I actually use this quite a bit now. 😄

**Comment by joker314** [comment]
Does anyone know how to get "notifications" for when someone comments in a repo/issue I'm "watching"; or if someone mentions me -- is it supposed to be by email or in my "Browse activity" tab or somewhere else?

**Comment by towerofnix** [comment]
@joker314 Well yeah, just check your notifications page? https://github.com/notifications -- it's the bell in the corner, by your user avatar.

Notifications for issues you've commented in (as well as issues you've manually subscribed to) will also show up in the "participating" section of the notifications page.

**Comment by joker314** [comment]
@towerofnix Thank you so much! I've gone to my notification settings and ticked "Web" for each thing; so hopefully that will give me some notifs. In the meantime, could you give mention me so I can test?
