### ISSUE TITLE
Messages page

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/scratch-client-omg#5]
May also want to implement admin messages (handy, since I have an admin message now). And dismissing those, I suppose, but meh!!!, that's hard to test since once a message is dismissed it's gone forever! So I'm not going to worry about that for now.

**Comment by joker314** [comment]
Have you been a naughty child!!!

**Comment by towerofnix** [comment]
No. 😸

**Comment by towerofnix** [comment]
![Demo screenshot](https://user-images.githubusercontent.com/9948030/37806824-bfddf0fc-2e20-11e8-8b43-513115a9d2ef.png)
