### ISSUE TITLE
Studio page

### ISSUE THREAD

**Issue by towerofnix** [towerofnix/scratch-client-omg#6]
View/reply to comments, view/edit description, view list of/add projects, view list of/add curators/managers, etc.

**Comment by joker314** [comment]
and delete studio; change thumbnail _maybe_

**Comment by towerofnix** [comment]
Studio data can't be written to ATM (e.g. you can't add projects or edit descriptions), but that's not any different from viewing your own projects; I'll leave those features for another time.
