### ISSUE TITLE
Better Description 

### ISSUE THREAD

**Issue by ktrvs** [towerofnix/scratch-client-omg#8]
> Scratch is crashing Firefox (nightly) right now and I need a way to view and reply to comments.

Well, technically not anymore, so we could maybe work on a newer description/tagline?

**Comment by towerofnix** [comment]
I'm not for crazy eye-catching lines, even if they sell better. But you're right that it's inaccurate. I'll fix it!

**Comment by towerofnix** [comment]
Thoughts on commit 7cfe8133777fe0f2b7c2018fffbbe4d88f1d00d7?

**Comment by joker314** [comment]
I think it closes this issue

(Just to see if GH crashes, this issue closes #8 -- infinite loops!)

**Comment by ktrvs** [comment]
👍
